apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-16T16:57:02Z","reason":"SucceededGetScale","message":"the
        HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2021-12-16T17:49:21Z","reason":"FailedGetResourceMetric","message":"the
        HPA was unable to compute the replica count: failed to get cpu utilization:
        unable to get metrics for resource cpu: unable to fetch metrics from resource
        metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2021-12-16T17:37:35Z","reason":"TooManyReplicas","message":"the
        desired replica count is more than the maximum replica count"}]'
    name: flaskdemo8082-autoscale
    namespace: miage
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: flaskdemo8082-autoscale
    targetCPUUtilizationPercentage: 20
