apiVersion: v1
kind: LimitRange
metadata:
  name: miage-namespace-lr
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 32Mi          
      cpu: 100m
    max:
      cpu: "2000m"
      memory: 1024Mi
    min:
      cpu: "100m"
      memory: 10Mi
    type: Container
