apiVersion: apps/v1
kind: Pod
metadata:
  name: flaskdemopod
spec:
  containers:
    - name: flaskdemo
      image: <VOTRE-IMAGE>
        resources:
        limits:
          memory: "500Mi"
          cpu: 1
        requests:
          memory: "100Mi"
          cpu: 0.1
